- name: system monit config
  become: true
  template: src=services/system.j2 dest={{ monit_include_path }}/system owner=root force=yes
  notify: restart monit
  when: monit_service_system

- name: disk monit config
  become: true
  template: src=services/disk.j2 dest={{ monit_include_path }}/disk owner=root force=yes
  notify: restart monit
  when: monit_service_disk

- name: consul monit config
  become: true
  template: src=services/consul.j2 dest={{ monit_include_path }}/consul owner=root force=yes
  notify: restart monit
  when: monit_service_consul

- name: vault monit config
  become: true
  template: src=services/vault.j2 dest={{ monit_include_path }}/vault owner=root force=yes
  notify: restart monit
  when: vault

- name: mariadb monit config
  become: true
  template: src=services/mariadb.j2 dest={{ monit_include_path }}/mariadb owner=root force=yes
  notify: restart monit
  when: monit_service_mariadb

- name: postfix monit config
  become: true
  template: src=services/postfix.j2 dest={{ monit_include_path }}/postfix owner=root force=yes
  notify: restart monit
  when: monit_service_postfix

- name: jenkins monit config
  become: true
  template: src=services/jenkins.j2 dest={{ monit_include_path }}/jenkins owner=root force=yes
  notify: restart monit
  when: monit_service_jenkins

- name: nexus monit config
  become: true
  template: src=services/nexus.j2 dest={{ monit_include_path }}/nexus owner=root force=yes
  notify: restart monit
  when: monit_service_nexus

- name: rsyslog monit config
  become: true
  template: src=services/rsyslog.j2 dest={{ monit_include_path }}/rsyslog owner=root force=yes
  notify: restart monit
  when: monit_service_rsyslog

- name: ntpd monit config
  become: true
  template: src=services/ntpd.j2 dest={{ monit_include_path }}/ntpd owner=root force=yes
  notify: restart monit
  when: monit_service_ntpd

- name: loginsight_agent monit config
  become: true
  template: src=services/loginsight_agent.j2 dest={{ monit_include_path }}/loginsight_agent owner=root force=yes
  notify: restart monit
  when: monit_service_loginsight_agent
